- name: create projects directory
  file:
    path: /vagrant/projects
    state: directory

# - name: clone repos
#   with_items: vagrant_repos
#   git:
#     repo: "{{item.url}}"
#     dest: "/vagrant/projects/{{item.dest}}"

- name: install nodejs legacy
  sudo: yes
  apt:
    pkg: nodejs-legacy
    state: latest

- name: get npm binary
  get_url:
    url: https://www.npmjs.org/install.sh
    validate_certs: no
    dest: /tmp/npm-install.sh

- name: install npm
  sudo: yes
  command: bash /tmp/npm-install.sh
  args:
    creates: /usr/bin/npm

- name: install node modules
  npm:
    path: /vagrant/projects/frontend/

- name: install gulp
  sudo: yes
  npm:
    global: yes
    state: latest
    name: gulp
